// Code generated by MockGen. DO NOT EDIT.
// Source: ./interface.go

// Package mock_usecases is a generated GoMock package.
package mocks


import (
	model "app/model"
	context "context"
	reflect "reflect"
	


	gomock "github.com/golang/mock/gomock"
)

// MockStudentRepo is a mock of StudentRepo interface.
type MockStudentRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStudentRepoMockRecorder
}

// MockStudentRepoMockRecorder is the mock recorder for MockStudentRepo.
type MockStudentRepoMockRecorder struct {
	mock *MockStudentRepo
}

// NewMockStudentRepo creates a new mock instance.
func NewMockStudentRepo(ctrl *gomock.Controller) *MockStudentRepo {
	mock := &MockStudentRepo{ctrl: ctrl}
	mock.recorder = &MockStudentRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStudentRepo) EXPECT() *MockStudentRepoMockRecorder {
	return m.recorder
}

// GetAll mocks base method.
func (m *MockStudentRepo) GetAll(ctx context.Context) ([]model.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", ctx)
	ret0, _ := ret[0].([]model.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAll indicates an expected call of GetAll.
func (mr *MockStudentRepoMockRecorder) GetAll(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockStudentRepo)(nil).GetAll), ctx)
}

// GetOneByID mocks base method.
func (m *MockStudentRepo) GetOneByID(ctx context.Context, id int) (model.Student, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOneByID", ctx, id)
	ret0, _ := ret[0].(model.Student)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOneByID indicates an expected call of GetOneByID.
func (mr *MockStudentRepoMockRecorder) GetOneByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOneByID", reflect.TypeOf((*MockStudentRepo)(nil).GetOneByID), ctx, id)
}

// InsertOne mocks base method.
func (m *MockStudentRepo) InsertOne(ctx context.Context, c *model.Student) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertOne", ctx, c)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertOne indicates an expected call of InsertOne.
func (mr *MockStudentRepoMockRecorder) InsertOne(ctx, c interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertOne", reflect.TypeOf((*MockStudentRepo)(nil).InsertOne), ctx, c)
}
